// Build step: compile the two standalone games into a single index.html.
//
//   src/desktop.html  ─┐
//                      ├─►  index.html   (committed; this is what GitHub Pages serves)
//   src/mobile.html   ─┘
//
// index.html holds BOTH games inlined as escaped strings. At runtime it reads
// ?v=desktop / ?v=mobile (or sniffs the device) and drops the chosen game into
// a full-page <iframe srcdoc=…>, so the two games' scripts/DOM never collide
// and only one ever executes.
//
// Edit the games in src/. Never hand-edit index.html — run `npm run build`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(root, p), 'utf8');

// Escape a game's full HTML so it can live inside a JS template literal AND not
// prematurely terminate the wrapping <script>. (\\/script and \\!-- decode back
// to </script and <!-- inside the string, so the game itself is unchanged.)
function esc(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/<\/(script)/gi, '<\\/$1')
    .replace(/<!--/g, '<\\!--');
}

const desktop = esc(read('src/desktop.html'));
const mobile = esc(read('src/mobile.html'));

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#0a0812">
<title>The Bread Zaddy</title>
<!-- ⚠️ AUTO-GENERATED by \`npm run build\` from src/desktop.html + src/mobile.html.
     Do not edit this file directly — edit the sources in src/ and rebuild. -->
<style>
  html, body { margin: 0; height: 100%; background: #0a0812; }
  #game { display: block; border: 0; width: 100vw; height: 100vh; }
</style>
</head>
<body>
<!-- Both games live in this one file. ?v=desktop / ?v=mobile picks one;
     with no param we sniff the device (phone -> mobile, else -> desktop).
     The chosen game runs in an iframe so the two games' scripts/DOM never
     collide and only one ever executes. -->
<iframe id="game" title="The Bread Zaddy" allow="autoplay"></iframe>
<script>
const GAMES = {
  desktop: \`${desktop}\`,
  mobile: \`${mobile}\`,
};
(function () {
  const forced = new URLSearchParams(location.search).get('v');
  let v;
  if (forced === 'mobile' || forced === 'desktop') {
    v = forced;
  } else {
    const ua = navigator.userAgent || '';
    const phoneUA = /Mobi|Android|iPhone|iPod/i.test(ua);
    const coarse = window.matchMedia && window.matchMedia('(pointer: coarse)').matches;
    const narrow = Math.min(window.innerWidth, window.innerHeight) <= 820;
    v = (phoneUA || (coarse && narrow)) ? 'mobile' : 'desktop';
  }
  const f = document.getElementById('game');
  // Give the game keyboard focus (desktop is WASD-driven) once it loads.
  f.addEventListener('load', () => { try { f.contentWindow.focus(); } catch (e) {} });
  f.srcdoc = GAMES[v];
})();
</script>
<noscript>This game requires JavaScript — please enable it to play. 🍞</noscript>
</body>
</html>
`;

writeFileSync(join(root, 'index.html'), html);
console.log(`built index.html (${html.length} bytes) from src/desktop.html + src/mobile.html`);
